apps/game_services_web/lib/game_services_web/router.ex
defmodule GameServicesWeb.Router do
  @moduledoc false
  use GameServicesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Authentication.AuthenticationPipeline
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GameServicesWeb do
    pipe_through :browser
    resources "/tickets", TicketController
    resources "/credentials", CredentialController
    resources "/users", UserController
    get "/", PageController, :index
    get "/login", LoginController, :index
    post "/login", LoginController, :login
    get "/logout", LoginController, :logout
    get "/registration", RegistrationController, :index
    post "/registration", RegistrationController, :register
  end

  # Other scopes may use custom stacks.
  # scope "/api", GameServicesWeb do
  #   pipe_through :api
  # end
end

apps/game_services_web/lib/game_services_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed and maintainability.</p>
</section>

<section>
  <article>
    <h2>Connection Status</h2>
    <ul>Authentication Status: <%= Authentication.get_connection_auth_status(@conn) %></ul>
    <h2>Links</h2>
    <ul><%= link("User", to: Routes.user_path(@conn, :index)) %></ul>
    <ul><%= link("Credential", to: Routes.credential_path(@conn, :index)) %></ul>
    <ul><%= link("User Registration", to: Routes.registration_path(@conn, :index)) %></ul>
    <ul><%= link("Login", to: Routes.login_path(@conn, :index)) %></ul>
    <ul><%= link("Logout", to: Routes.login_path(@conn, :logout)) %></ul>
  </article>
</section>